server:
  port: 8100
  servlet:
    path: /

spring:
  profiles:
    active: dev
  application:
    name: calm-auth
  thymeleaf:
    mode: LEGACYHTML5
  resources: # 指定静态资源的路径
      static-locations: classpath:/static/,classpath:/templates/
  redis:
    host: 127.0.0.1
    port: 6379
    password: redhat
    database: 1

# shiro 不拦截路径
shiro:
  anon:
    path:
      # 静态资源
      - /css/**
      - /img/**
      # spring cloud 健康检查
      - /actuator/**
      # oauth登录页面
      - /login
      # jelly 登录
      - /jelly/login/**

tencent:
  baseUrl: https://graph.qq.com
  authorizeURL: ${tencent.baseUrl}/oauth2.0/authorize
  accessTokenURL: ${tencent.baseUrl}/oauth2.0/token
  getUserInfoURL: ${tencent.baseUrl}/user/get_user_info
  getOpenIDURL: ${tencent.baseUrl}/oauth2.0/me
  clientId: 101494574
  clientSecret: 22e81b9bb632922b1095d0de329c9a35
  redirectURI: http://test.hejinyo.cn/api/oauth/v2
  scope: get_user_info