server:
  port: 8100
  servlet:
    path: /

spring:
  profiles:
    active: dev
  application:
    name: calm-auth
  thymeleaf:
    mode: LEGACYHTML5
  resources: # 指定静态资源的路径
      static-locations: classpath:/static/,classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: redhat
  redis:
    host: 127.0.0.1
    port: 6379
    password: redhat
    database: 1

# shiro 不拦截路径
shiro:
  anon:
    path:
      # 静态资源
      - /css/**
      - /img/**
      # spring cloud 健康检查
      - /actuator/**
      # oauth登录页面
      - /login
      # jelly 登录
      - /jelly/login/**