spring:
  application:
    name: calm-mail
  thymeleaf:
    mode: LEGACYHTML5
  resources: # 指定静态资源的路径
      static-locations: classpath:/static/,classpath:/templates/
  mail:
    host: smtp.hejinyo.cn
    username: jelly@hejinyo.cn
    password: Redhat@2018
    default-encoding: utf-8

server:
  port: 8220
  servlet:
    path: /

eureka:
  client:
    service-url:
      defaultZone: http://hejinyo:password@localhost:8000/eureka/
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 30
  instance:
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${server.port}
    #状态页面和健康指标
    statusPageUrlPath: ${server.servlet.path}/actuator/info
    healthCheckUrlPath: ${server.servlet.path}/actuator/health

# Feign 开启 Hystrix
feign:
  hystrix:
    enabled: true

info:
  app:
    name: calm-mail
    version: 1.0